import { Component, OnInit, Input } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
    selector: 'choice-emb-color-modal',
    templateUrl: './choice.embcolor.modal.component.html'
})
export class ChoiceEmbColorModalComponent implements OnInit {

    @Input() modal_title;
    @Input() modal_content;
    selected_color: string = "#94A9C2";
    color_pallete: any[] = [
        { color: '#2C3445', label: 'Black' },
        { color: '#2A374A', label: 'Blue Ribbon' },
        { color: '#333C53', label: 'Light Navy' },
        { color: '#7991B7', label: 'Cosmic Sky' },
        { color: '#94A9C2', label: 'Lake Blue' },
        { color: '#4B6B99', label: 'Jay Blue' },
        { color: '#2B5392', label: 'Jamie Blue' },
        { color: '#1E4482', label: 'Royal' },
        { color: '#234877', label: 'Blue Suede' },
        { color: '#214F77', label: 'Imperial Blue' },
        { color: '#5A89AA', label: 'Caribbean Blue' },
        { color: '#3B688D', label: 'Slate Blue' },
        { color: '#233D5B', label: 'Blue Ink' },
        { color: '#005796', label: 'Blue' },
        { color: '#84A8C8', label: 'Baby Blue' },
        { color: '#95B5CF', label: 'Ice Blue' },
        { color: '#277EB7', label: 'Dolphin Blue' },
        { color: '#005592', label: 'Fire Blue' },
        { color: '#2E89BD', label: 'Dolphin Blue' },
        { color: '#006DA7', label: 'Ocean Blue' },
        { color: '#0081B6', label: 'Baltic Blue' },
        { color: '#70A8C6', label: 'Sky Blue' },
        { color: '#407497', label: 'Pale Purple' },
        { color: '#273C52', label: 'Blue' },
        { color: '#CD8126', label: 'Pollen Gold' },
        { color: '#E7982D', label: 'Buttercup' },
        { color: '#F0AF45', label: 'Star Gold' },
        { color: '#F5D6A1', label: 'Pale Yellow' },
        { color: '#F4DAAB', label: 'Wheat' },
        { color: '#F0DDA6', label: 'Sunshine' },
        { color: '#F5D777', label: 'Lemon' },
        { color: '#FACE5A', label: 'Moonbeam' },
        { color: '#FAC74B', label: 'Star Gold' },
        { color: '#F1B13C', label: 'Manila' },
        { color: '#E57821', label: 'Mango' },
        { color: '#F48CD', label: 'Merit Gold' },
        { color: '#FFA617', label: 'Buttercup' },
        { color: '#FFB14', label: 'Manila' },
        { color: '#FFBC16', label: 'Canary' },
        { color: '#FFC71D', label: 'Daffodil' },
        { color: '#EFC82C', label: 'Canary' },
        { color: '#E6C44A', label: 'Daffodil' },
        { color: '#ECE2AB', label: 'PaleYellow' },
        { color: '#E9DEBA', label: 'Celery' },
        { color: '#EAE3B9', label: 'Medium Yellow' },
        { color: '#F3DA68', label: 'Lemon' },
        { color: '#CDAF4C', label: 'Yellow' },
        { color: '#A1822A', label: 'Black Eyed Susie' },
        { color: '#E2BC51', label: 'Star Gold' },
        { color: '#CF982D', label: 'Pollen Gold' },
        { color: '#A9792A', label: 'Bullion' },
        { color: '#20544E', label: 'Green' },
        { color: '#008173', label: 'Peppermint' },
        { color: '#4FAC98', label: 'Pale Green' },
        { color: '#86CCBF', label: 'Seafrost' },
        { color: '#00B9AC', label: 'Aqua Pearl' },
        { color: '#009986', label: 'Bluestone' },
        { color: '#00867A', label: 'Brite Jade' },
        { color: '#00625E', label: 'Imperial Aqua' },
        { color: '#008B87', label: 'M. D. Green' },
        { color: '#8EC4C3', label: 'Light Blue' },
        { color: '#61A9AC', label: 'Aquamarine' },
        { color: '#148589', label: 'M. D. Green' },
        { color: '#006D70', label: 'M. D. Green' },
        { color: '#6CA9B2', label: 'Basic Turquoise' },
        { color: '#4698A5', label: 'Capri' },
        { color: '#006473', label: 'Mallard Blue' },
        { color: '#007080', label: 'Dark Aqua Green' },
        { color: '#00B3C9', label: 'Periwinkle' },
        { color: '#1BBBC9', label: 'Indian Ocean Blue' },
        { color: '#00A9C2', label: 'Aquamarine' },
        { color: '#008CAC', label: 'Dark Blue/Green' },
        { color: '#00819B', label: 'Blue/Green' },
        { color: '#93C2D1', label: 'Cadet Blue' },
        { color: '#599AB5', label: 'Ozone' },
        { color: '#007D9B', label: 'Pretty Blue' },
        { color: '#005F7E', label: 'Peacock' },
        { color: '#0071A3', label: 'Baltic Blue' },
        { color: '#5A405C', label: 'Medium Purple' },
        { color: '#9A688E', label: 'Rose Dust' },
        { color: '#C5ADC5', label: 'Light Pink' },
        { color: '#C7A1BF', label: 'Carnatio' },
        { color: '#A26689', label: 'Hot Pink' },
        { color: '#5C3551', label: 'Medium Purple' },
        { color: '#7A3B6D', label: 'Dark Red' },
        { color: '#953C73', label: 'Hot Peony' },
        { color: '#D66399', label: 'Wild Pink' },
        { color: '#E192B8', label: 'Petal Pink' },
        { color: '#CF4D88', label: 'Ruby Glint' },
        { color: '#BF2F6E', label: 'Ruby Glint' },
        { color: '#9C1F54', label: 'Cherrystone' },
        { color: '#B71855', label: 'Dark Pink' },
        { color: '#BE3763', label: 'Dark Pink' },
        { color: '#E2AFC5', label: 'Pink' },
        { color: '#E6BAC9', label: 'Crystal Pink' },
        { color: '#E98BA3', label: 'Dusty Rose' },
        { color: '#CC4B6D', label: 'Cerise' },
        { color: '#A90042', label: 'Red' },
        { color: '#BD1D44', label: 'Wildfire' },
        { color: '#D84660', label: 'Cerise' },
        { color: '#DC8B9A', label: 'Medium Pink' },
        { color: '#892533', label: 'Red Berry' },
        { color: '#B6F2F', label: 'Foxy Red' },
        { color: '#BE1422', label: 'Tuxedo Red' },
        { color: '#D42727', label: 'Saffron' },
        { color: '#DBE08C', label: 'Pebblestone' },
        { color: '#8D9949', label: 'Medium Green' },
        { color: '#3F5435', label: 'Holly' },
        { color: '#5A6E29', label: 'Meadow' },
        { color: '#7B9553', label: 'Green Dust' },
        { color: '#344D3B', label: 'Holly' },
        { color: '#3A793E', label: 'Kelly' },
        { color: '#488F52', label: 'Emerald' },
        { color: '#71AC6B', label: 'Neon Green' },
        { color: '#234F3B', label: 'Evergreen' },
        { color: '#008745', label: 'Kelly' },
        { color: '#459645', label: 'Emerald' },
        { color: '#6FA04D', label: 'Spruce' },
        { color: '#9ACE69', label: 'Sharp Green' },
        { color: '#EA146', label: 'Harvest Green' },
        { color: '#00914C', label: 'Vibrant Green' },
        { color: '#007047', label: 'Dark Green' },
        { color: '#00874F', label: 'Kelly' },
        { color: '#7ACE96', label: 'Pale Aqua' },
        { color: '#38A87D', label: 'Bluestone' },
        { color: '#00936D', label: 'Peppermint' },
        { color: '#007763', label: 'Jade' },
        { color: '#CCDBCF', label: 'Billowing Sail' },
        { color: '#AFD2C0', label: 'Bleached Aqua' },
        { color: '#6AC6A3', label: 'Pale Aqua' },
        { color: '#2B9F84', label: 'Seafoam' },
        { color: '#006253', label: 'Green Forest' },
        { color: '#F0B4A8', label: 'Flesh Pink' },
        { color: '#E38D81', label: 'Flamingo' },
        { color: '#AA4134', label: 'Dark Rust' },
        { color: '#E7B7A5', label: 'Peach' },
        { color: '#EFB296', label: 'Opaline' },
        { color: '#D58D64', label: 'Buff Orange' },
        { color: '#BA522F', label: 'Old Dark Tex Orange' },
        { color: '#CD7A4E', label: 'Toast' },
        { color: '#F4BC8B', label: 'Glow' },
        { color: '#F59E65', label: 'Chamois' },
        { color: '#FF6616', label: 'Pumpkin' },
        { color: '#ED532A', label: 'Paprika' },
        { color: '#F66943', label: 'Orange' },
        { color: '#DD3823', label: 'Sunkist' },
        { color: '#E15445', label: 'Coral' },
        { color: '#FA8972', label: 'Arctic Ice' },
        { color: '#F4BCAC', label: 'Peach' },
        { color: '#EED1CA', label: 'Rosewater' },
        { color: '#EBC5C0', label: 'Pink Mist' },
        { color: '#E9ACA5', label: 'Flesh Pink' },
        { color: '#F7887D', label: 'Flamingo' },
        { color: '#C9524B', label: 'Dark Rust' },
        { color: '#8C2F33', label: 'Red Bittersweet' },
        { color: '#E2433D', label: 'Paprika' },
        { color: '#E9A09B', label: 'Emily Pink' },
        { color: '#E17578', label: 'Pink Icing' },
        { color: '#A12831', label: 'Red Berry' },
        { color: '#2C356B', label: 'Violet Blue' },
        { color: '#4565A2', label: 'Violet' },
        { color: '#939DC3', label: 'Pastel Lilac' },
        { color: '#515E97', label: 'Violet' },
        { color: '#353862', label: 'Blue Ink' },
        { color: '#413F79', label: 'Dark Purple/Navy' },
        { color: '#534680', label: 'Purple Accent' },
        { color: '#8E8BB8', label: 'Pale Purple' },
        { color: '#A67DA9', label: 'Medium Pink' },
        { color: '#6E4981', label: 'Mulberry' },
        { color: '#613267', label: 'Mulberry' },
        { color: '#4E3568', label: 'Purple Shadow' },
        { color: '#816C9D', label: 'Iris' },
        { color: '#A799BB', label: 'Violet' },
        { color: '#58496F', label: 'Purple Accent' },
        { color: '#443555', label: 'Purple Accent' },
        { color: '#4E4564', label: 'Blackberry' },
        { color: '#7E7897', label: 'Sterling' },
        { color: '#74677E', label: 'Light Grape' },
        { color: '#514C5E', label: 'Light Midnight' },
        { color: '#938C9E', label: 'Thistle' },
        { color: '#798191', label: 'Purple Cloud' },
        { color: '#40495F', label: 'Light Midnight' },
        { color: '#47596E', label: 'Lake Blue' },
        { color: '#ACBFCB', label: 'Illusion Blue' },
        { color: '#7691A1', label: 'Country Blue' },
        { color: '#4F6B80', label: 'Slate Blue' },
        { color: '#4E2A36', label: 'Plum' },
        { color: '#653D47', label: 'Dark Maroon' },
        { color: '#9C7178', label: 'Light Pink' },
        { color: '#B599A1', label: 'Rose Beige' },
        { color: '#4D303D', label: 'Plum' },
        { color: '#632F3D', label: 'Warm Wine' },
        { color: '#9C4F64', label: 'K. A. Bronze' },
        { color: '#994262', label: 'Burgundy' },
        { color: '#732E4A', label: 'Brushed Burgundy' },
        { color: '#8D3152', label: 'Cranberry' },
        { color: '#D4628E', label: 'Begonia' },
        { color: '#EBADBF', label: 'Orchid Pink' },
        { color: '#EFBBC1', label: 'Crystal Pink' },
        { color: '#E49CA7', label: 'Pink Mist' },
        { color: '#9F233F', label: 'Atom Red' },
        { color: '#6E2B38', label: 'Wine' },
        { color: '#612533', label: 'Wine' },
        { color: '#782B3C', label: 'Burgundy' },
        { color: '#8C2842', label: 'Cabernet' },
        { color: '#BA3051', label: 'Wildfire' },
        { color: '#E86276', label: 'Shell Pink' },
        { color: '#EEB2BC', label: 'Orchid Pink' },
        { color: '#EABABA', label: 'Bisque' },
        { color: '#E9B3B1', label: 'Desert Bloom' },
        { color: '#EA9595', label: 'Emily Pink' },
        { color: '#DA4751', label: 'Scarlet' },
        { color: '#812833', label: 'Dark Orange/Red' },
        { color: '#234D67', label: 'Salem Blue' },
        { color: '#3C7D9E', label: 'Pale Purple' },
        { color: '#88BBCF', label: 'Pale Blue' },
        { color: '#9ABACA', label: 'Cadet Blue' },
        { color: '#4C7283', label: 'Wonder Blue' },
        { color: '#1F3F4A', label: 'Deep Windsor' },
        { color: '#154B4B', label: 'Blue Spruce' },
        { color: '#397474', label: 'Imperial Aqua' },
        { color: '#375B63', label: 'Deep Atlantic' },
        { color: '#2D4851', label: 'Deep Windsor' },
        { color: '#80979E', label: 'Blue Gray' },
        { color: '#EDCE88', label: 'Pale Yellow' },
        { color: '#D2A142', label: 'Black Eyed Susie' },
        { color: '#B88B30', label: 'Black Eyed Susie' },
        { color: '#927038', label: 'Autumn Green' },
        { color: '#765B34', label: 'Earthen Tan' },
        { color: '#C0B085', label: 'Wheat' },
        { color: '#EDE0BF', label: 'Tusk' },
        { color: '#C1B597', label: 'Light Green/Yellow' },
        { color: '#ABA37E', label: 'Silver Fern' },
        { color: '#776B4C', label: 'Desert Cactus' },
        { color: '#414137', label: 'Hedge' },
        { color: '#7B7966', label: 'Arcadian Green' },
        { color: '#A7A595', label: 'Pale Gray Green' },
        { color: '#999A87', label: 'Pussywillow Gray' },
        { color: '#6B6D59', label: 'Medium Green/Yellow' },
        { color: '#505443', label: 'Green/Yellow' },
        { color: '#2C453D', label: 'Dark Green' },
        { color: '#4E6B61', label: 'Green Forest' },
        { color: '#799C97', label: 'Pale Blue' },
        { color: '#A3BCB8', label: 'Sprite' },
        { color: '#8FC3B4', label: 'Pale Green' },
        { color: '#0E4E3F', label: 'Dark Green' },
        { color: '#21453B', label: 'Evergreen' },
        { color: '#145A4A', label: 'Green Bay' },
        { color: '#588773', label: 'Blue Surf' },
        { color: '#9EBDA2', label: 'Mint' },
        { color: '#BED1B2', label: 'Pastel Green' },
        { color: '#516150', label: 'Water Lilly' },
        { color: '#364033', label: 'Dark Army Green' },
        { color: '#3D493F', label: 'Mitchell Green' },
        { color: '#6A7A6A', label: 'Harbor Green' },
        { color: '#BAC19F', label: 'Pastel Green' },
        { color: '#C1C596', label: 'Lime Cream' },
        { color: '#B6AF7C', label: 'Green Haze' },
        { color: '#978C54', label: 'Crescent Moon' },
        { color: '#787346', label: 'Medium Green/Yellow' },
        { color: '#484634', label: 'Green' },
        { color: '#808033', label: 'Tamarack' },
        { color: '#8D8430', label: 'Crescent Moon' },
        { color: '#B5A348', label: 'Green/Gold' },
        { color: '#B49F55', label: 'Hemp' },
        { color: '#957F3D', label: 'Medium Yellow/Green' },
        { color: '#715C2D', label: 'Desert Cactus' },
        { color: '#C98D47', label: 'Pollen Gold' },
        { color: '#D2A970', label: 'Yellow Gold' },
        { color: '#E4BA82', label: 'Glow' },
        { color: '#F0A653', label: 'Scholastic' },
        { color: '#C2793F', label: 'Almond' },
        { color: '#9C562F', label: 'Orange/Brown' },
        { color: '#DBA272', label: 'Impala' },
        { color: '#AF7F56', label: 'Sirocco' },
        { color: '#9E6947', label: 'Wicker' },
        { color: '#7E4833', label: 'Light Cocoa' },
        { color: '#794337', label: 'Mushroom' },
        { color: '#A07155', label: 'Fawn' },
        { color: '#AE7D5A', label: 'Light Bronze' },
        { color: '#DCC7B3', label: 'Ecru' },
        { color: '#CCBAA4', label: 'Seashell' },
        { color: '#A29082', label: 'Taupe' },
        { color: '#7C6054', label: 'Dark Olive Green' },
        { color: '#483933', label: 'Egyptian Brown' },
        { color: '#614E3F', label: 'Fungi' },
        { color: '#846A57', label: 'Light Cocoa' },
        { color: '#D2B99D', label: 'Sea Mist' },
        { color: '#D4B18F', label: 'Cream' },
        { color: '#C1956C', label: 'Gold' },
        { color: '#8F7154', label: 'Beige' },
        { color: '#AB8F6A', label: 'Olive Drab' },
        { color: '#A78C61', label: 'Candied Ginger' },
        { color: '#795D3C', label: 'Earthen Tan' },
        { color: '#602C31', label: 'Warm Wine' },
        { color: '#843A37', label: 'Burgundy' },
        { color: '#A46462', label: 'K. A. Bronze' },
        { color: '#AD726B', label: 'Mahogany Rose' },
        { color: '#AC837A', label: 'Tawny Birch' },
        { color: '#774D4D', label: 'Dark Brown' },
        { color: '#593032', label: 'Dark Sepia' },
        { color: '#B79B8F', label: 'Whisper Pink' },
        { color: '#775854', label: 'Dark Brown' },
        { color: '#493937', label: 'Espresso' },
        { color: '#6E5851', label: 'Dark Brown' },
        { color: '#987D6E', label: 'Shadow Gray' },
        { color: '#DCBAA5', label: 'Alesan' },
        { color: '#C19988', label: 'Amber Beige' },
        { color: '#71463B', label: 'Mushroom' },
        { color: '#5E3E35', label: 'Brown' },
        { color: '#423734', label: 'Egyptian Brown' },
        { color: '#8B796C', label: 'String' },
        { color: '#CDBAA6', label: 'Ivory' },
        { color: '#DCD2BD', label: 'Aspen White' },
        { color: '#E9E5DC', label: 'Natural White' },
        { color: '#7C7669', label: 'Medium Green/Yellow' },
        { color: '#8D867A', label: 'Pale Grey' },
        { color: '#B3A697', label: 'Platinum' },
        { color: '#6D6258', label: 'Vertiver Green' },
        { color: '#5D5147', label: 'Dark Grey' },
        { color: '#3B3431', label: 'Dark Grey' },
        { color: '#424047', label: 'Dark Grey' },
        { color: '#8A8689', label: 'Silvery Gray' },
        { color: '#CFCDCA', label: 'Dawn Blue' },
        { color: '#B8B5AF', label: 'White Sand' },
        { color: '#726967', label: 'Charcoal' },
        { color: '#575251', label: 'Twilight' },
        { color: '#6B6869', label: 'Metal' },
        { color: '#BCBCB8', label: 'Pearl Gray' },
        { color: '#C7C9C6', label: 'Palest Ivory' },
        { color: '#5E605E', label: 'Medium Grey' },
        { color: '#7A7976', label: 'Moon Mist' },
        { color: '#C2C4BF', label: 'Vapor' },
        { color: '#A9AFB2', label: 'Traditional Gray' },
        { color: '#899193', label: 'Banner Gray' },
        { color: '#A3AFB3', label: 'Pastel Blue' },
        { color: '#535A63', label: 'Gull' },
        { color: '#2A2E36', label: 'Black' },
        { color: '#B5C6D6', label: 'Cadet Blue' },
        { color: '#BBC5CE', label: 'Cadmium Orange' },
        { color: '#A3AFB3', label: 'Pale Silver' },
        { color: '#6E747B', label: 'Metal' },
        { color: '#3B3F45', label: 'Black' },
        { color: '#E9E7E7', label: 'Natural White' },
        { color: '#EAE8EE', label: 'Blue Blush' },
        { color: '#E7E7F4', label: 'Bright White' },
        { color: '#E3E5FB', label: 'Bright White' },
        { color: '#E0E4FF', label: 'Billowing Sail' },
        { color: '#28292A', label: 'Black' },
        { color: '#29282A', label: 'Diamond Black' },
        { color: '#2A2829', label: 'Black' },
        { color: '#282A2C', label: 'Ruby Black' },
        { color: '#2B2B30', label: 'Sapphire Black' }
    ]

  constructor(public activeModal: NgbActiveModal) {
  }

  ngOnInit() {
    }

  set_preview_color(color) {
      this.selected_color = color;
  }
}
